### ISSUE TITLE
作者啥时候更新v3啊

### ISSUE THREAD

**Issue by RAINighty** [KaguraMika/bili-suit-v2#1]
明天的猫雷我还不知道赶不赶得上，求求作者大大了

**Comment by RAINighty** [comment]
如果打点米可以明天出的话我觉得还是值得的

**Comment by KaguraMika** [comment]
NOT a issue.

**Comment by RAINighty** [comment]
求求了

**Comment by KaguraMika** [comment]
Actually, V3 also meet a problem, if someone want to take over this project, I can transfer it to him.

**BUT YOU NEED TO FOLLOW THE GPL-3.0**

**Comment by RAINighty** [comment]
好吧，如果您能明天下午五六点钟之前解决v3遇到的问题并发布的话，我愿意support两三百米的

**Comment by RAINighty** [comment]
> Actually, V3 also meet a problem, if someone want to take over this project, I can transfer it to him.
> 
> **BUT YOU NEED TO FOLLOW THE GPL-3.0**

您好，请问您可以把v3现在的码发我吗？虽然用不了，但是我想试试能不能帮上忙

**Comment by RAINighty** [comment]
> > Actually, V3 also meet a problem, if someone want to take over this project, I can transfer it to him.
> > **BUT YOU NEED TO FOLLOW THE GPL-3.0**
> 
> 您好，请问您可以把v3现在的码发我吗？虽然用不了，但是我想试试能不能帮上忙

以及您知道是哪一部分的api无法使用了吗

**Comment by Sam5440** [comment]
What's the problem in v3? I think you can set it public then we solve it together,ballballyou

**Comment by FengXin2125** [comment]
https://github.com/lllk140/BiliSuitNumberBuy
已经有人做出来了，是否可以参考一下。
