### ISSUE TITLE
还会有新版本吗o(╥﹏╥)o

### ISSUE THREAD

**Issue by dbwuac** [KaguraMika/bili-suit-v2#3]

**Comment by KaguraMika** [comment]
暂时没有空管这边
不过如果有手抢出现  `{"code":26134,"message":"当前抢购人数过多，请稍后再试～","ttl":1}` 的情况，可以反馈给我
描述的情况尽量详细点

**Comment by dbwuac** [comment]
> 

也就说，现在还能用v2版本吗？v3链接失效了

**Comment by KaguraMika** [comment]
> > 
> 
> 也就说，现在还能用v2版本吗？v3链接失效了

不能，表单差太多了，Web端的下单也被屏蔽了

**Comment by dbwuac** [comment]
> > > 
> > 
> > 
> > 也就说，现在还能用v2版本吗？v3链接失效了
> 
> 不能，表单差太多了，Web端的下单也被屏蔽了

那......还有别的地方可以下载到么😭

**Comment by KaguraMika** [comment]
🏳️🏳️🏳️
